# Generated by Django 4.2.7 on 2023-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
