# Generated by Django 5.0 on 2023-12-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_mill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
