# Generated by Django 5.0 on 2023-12-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_diposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Diposit',
        ),
        migrations.DeleteModel(
            name='Mill',
        ),
    ]
