# Generated by Django 5.0 on 2023-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_or_return',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='establish_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='mill_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
