# Generated by Django 5.0 on 2023-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_bill_due_or_return_bill_establish_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='diposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
