# Generated by Django 5.0 on 2023-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_alter_bill_diposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='diposit',
            name='reasone',
            field=models.CharField(choices=[('B', 'Bazar'), ('E', 'Establishment')], default='B', max_length=1),
        ),
    ]
